#!/bin/sh
#
# Let args be all of the arguments, and switch on the number of them
#
case $# in
#
#
# Do normal processing
#
    2)
    echo ' '
    echo "Processing file  $1  to produce file  $2"
    echo 'Each raw entry produces two <item>|<item> entries'
    echo ' '
    perl ./write_syns.perl $1 > $2
    ;;
#
#
# Otherwise, print the command usage
#
    *)
    echo ' '
    echo 'Please specify'
    echo '     write_syns <input file> <output file>'
    echo ' '
    ;;
esac
exit
