#!/usr/bin/perl -w

use strict;

# call on mrconso.suppressed to generate output like
# C0000039|SNMI,NDFRT,MSH,LNC,MTH,SNOMEDCT
# C0000052|SNMI,NDFRT,MSH,LNC,SNM,MTH,SNOMEDCT
# which will need calling atom_codes and split_string_completely

# Call on mrconso.suppressed, whose fields 0 and 11 are CUI and SRC, e.g.

# C0000005|MSH
# C0000005|MSH
# C0000039|MSH
# C0000039|NDFRT
# C0000039|MTH
# C0000039|MSH
# C0000039|NDFRT
# C0000039|MSH
# C0000039|MSH
# C0000039|NDFRT

my ( $Line, $CUI, $Source );
my %CUIHash;

while ( <> ) {
    chomp;
    $Line = $_;
    ( $CUI, $Source ) = ( split /\|/, $Line )[0,11];
    $CUIHash{$CUI}{$Source} = 1;
} # while ( <> )

foreach $CUI ( sort keys %CUIHash ) {
    my $String = "$CUI";
    my $Sources = join ",", keys %{$CUIHash{$CUI}};
    print "$String|$Sources\n";
} # foreach $CUI ( sort keys %CUIHash )
