#!/bin/sh
# derived from 05Filter/0doit3.strict.check

date

cd Filter/ALLFILES.strict

ERRORFILES=""

for FILE in mrconso.eng.chunk.[0-9][0-9][0-9][0-9]
do
   LINES=`cat $FILE | wc -l`
   FILTERED=`grep -c '^[yn]' $FILE.filtered`
   if [ $LINES -eq $FILTERED ]
   then
      echo $FILE OK
   else
      echo $FILE $LINES $FILTERED
      ERRORFILES="$ERRORFILES $FILE"
   fi
done

if [ "$ERRORFILES" != "" ]
then
   echo files with errors:
   echo $ERRORFILES
   echo ""
   mv $ERRORFILES ..
   echo run the command
   echo cd Filter/ALLFILES.strict
   echo source ../../../dfbuilder.profile
   echo ./filter_mrconso_ALL -sEN 1000 $ERRORFILES
#   echo and then run 0doit3.strict.check
   echo and then run 04FilterStrictCheck
fi

echo DONE 
