#!/bin/sh

# The $MODEL parameter is currently not used.
MRRANK_FILE=$1
MODEL=$2
FLAGS=$3
INCREMENT=$4

shift 4

for FILENAME in $*
do
   NUMLINES=`cat $FILENAME | wc -l`
   echo filter_mrconso $FLAGS -p $INCREMENT -t $NUMLINES $FILENAME $FILENAME.filtered
   filter_mrconso $FLAGS -p $INCREMENT -t $NUMLINES $FILENAME $FILENAME.filtered
done
