#!/bin/sh -f
#
# Let args be all of the arguments, and switch on the number of them
#
case $# in
#
#
# Do normal processing
#
    2)
    echo ' '
    echo "Processing file  $1  to produce file  $2"
    echo 'Each raw entry produces two <item>|<item>|<cat>|<type> entries'
    echo ' '
    perl ./write_aas.perl $1 > $2
    ;;
#
#
# Otherwise, print the command usage
#
    *)
    echo ' '
    echo 'Please specify'
    echo '     write_aas <input file> <output file>'
    echo ' '
    ;;
esac
exit
